version: '3.8'
services:
  web:
    image: nginx:alpine
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
